image: viaduck/ci

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
    - build
    - test

build:linux:x86_64:
    stage: build
    script:
        - mkdir build
        - cd build
        - cmake -GNinja ../ -DGTEST_SRC_DIR=/usr/src/googletest/
        - ninja
    artifacts:
        expire_in: 2h                   # do not pollute disk
        paths:
        - build/

test:linux:x86_64:
    stage: test
    script:
        - cd build
        - test/SecureMemory_Test             # runs gtest target
    dependencies:
    - build:linux:x86_64

